inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'ruby/compete/code_golf/**/*'
    - 'vendor/ruby/gems/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'ruby/**/*'

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'ruby/practice/classic_puzzle/medium/winamax-battle.rb' # bug in cop

Style/WhileUntilDo:
  Enabled: false

